name: applovin
description: Flutter Plugin Ad Network AppLovin
version: 0.0.1
author: Fernando Araujo <developgadget@gmail.com>
homepage: https://github.com/DevelopGadget/flutter_applovin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: developgadget.com.applovin
    pluginClass: ApplovinPlugin
